version: '3.8'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: dockerization/nginx/Dockerfile
    depends_on:
      - websocket
    ports:
      - "80:80"
      - "443:443"

  websocket:
    build: .
    ports:
      - "8765:8765"

  frontend:
    build: 
      context: /share/frontend
      dockerfile: Dockerfile
    ports:
      - "8301:80"
    restart: unless-stopped


  sourcebot:
    image: ghcr.io/sourcebot-dev/sourcebot:latest
    ports:
      - "3000:3000"  # Expose web interface
    volumes:
      - ./sourcebot-config.json:/data/config.json  # Mount config file
      - sourcebot-data:/data/.sourcebot  # Persist indexed data
    environment:
      - CONFIG_PATH=/data/config.json
      - SOURCEBOT_TELEMETRY_DISABLED=1  # Disable telemetry

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"  # Expose Postgres port to match default env settings
    environment:
      POSTGRES_DB: ${CHECKPOINTER_POSTGRES_DB}
      POSTGRES_USER: ${CHECKPOINTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CHECKPOINTER_POSTGRES_PASSWORD}
    volumes:
      - ./data/graph-memory:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sourcebot-data:  # Named volume for persistent storage

