services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: dockerization/nginx/Dockerfile
    depends_on:
      - websocket
    ports:
      - "80:80"
      - "443:443"

  websocket:
    build: .
    ports:
      - "8765:8765"
    env_file:
      - .env

    depends_on:
      - postgres
      - sourcebot
      - code-search-api

  frontend:
    build: 
      context: /share/frontend
      dockerfile: Dockerfile
    ports:
      - "8301:80"
    restart: unless-stopped

  sourcebot:
    image: ghcr.io/sourcebot-dev/sourcebot:latest
    ports:
      - "3000:3000"  # Expose web interface
    volumes:
      - ./sourcebot-config.json:/data/config.json  # Mount config file
      - sourcebot-data:/data/.sourcebot  # Persist indexed data
    environment:
      - CONFIG_PATH=/data/config.json
      - SOURCEBOT_TELEMETRY_DISABLED=1  # Disable telemetry

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"  # Expose Postgres port to match default env settings
    environment:
      POSTGRES_DB: ${CHECKPOINTER_POSTGRES_DB}
      POSTGRES_USER: ${CHECKPOINTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CHECKPOINTER_POSTGRES_PASSWORD}
    volumes:
      - ./data/graph-memory:/var/lib/postgresql/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  embedder:
    image: vllm/vllm-openai:latest
    ports:
      - "8001:8000"
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: --model Qodo/Qodo-Embed-1-1.5B --trust-remote-code

  code-search-api:
    build:
      context: ./code-search-api
      dockerfile: Dockerfile
    ports:
      - "${CODE_SEARCH_API_PORT:-8000}:8000"
    depends_on:
      - qdrant
      - embedder
    environment:
      - PORT=8000
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDER_URL=http://embedder:8000/v1/embeddings
      - CONFIG_PATH=/app/config.json
    volumes:
      - ./sourcebot-config.json:/app/config.json
      - ./code-search-api/data:/app/data

volumes:
  sourcebot-data:  # Named volume for persistent storage
  qdrant_data:  # Vector database storage
