version: '3.8'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: dockerization/nginx/Dockerfile
    depends_on:
      - websocket
    ports:
      - "80:80"
      - "443:443"
    # networks:
    #   - websocket-network

  websocket:
    build: .
    ports:
      - "8765:8765"
    # networks:
    #   - websocket-network


  sourcebot:
    image: ghcr.io/sourcebot-dev/sourcebot:latest
    ports:
      - "3000:3000"  # Expose web interface
    volumes:
      - ./sourcebot-config.json:/data/config.json  # Mount config file
      - sourcebot-data:/data/.sourcebot  # Persist indexed data
    environment:
      - CONFIG_PATH=/data/config.json
      - SOURCEBOT_TELEMETRY_DISABLED=1  # Disable telemetry

volumes:
  sourcebot-data:  # Named volume for persistent storage

# networks:
#   websocket-network:
