version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - code-search-network

  embedder:
    image: vllm/vllm-openai:latest
    ports:
      - "8001:8000"
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    # environment:
    #   - VLLM_USE_V1=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: --model Qodo/Qodo-Embed-1-1.5B --trust-remote-code
    networks:
      - code-search-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - embedder
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDER_URL=http://embedder:8000/v1/embeddings
      - CONFIG_PATH=/app/repos_config.json
    volumes:
      - ./repos_config.json:/app/repos_config.json
    networks:
      - code-search-network

networks:
  code-search-network:

volumes:
  qdrant_data:
