services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6336:6333"  # Changed from 6333
      - "6337:6334"  # Changed from 6334
    volumes:
      - ./data/quadrant:/qdrant/storage

  embedder:
    image: vllm/vllm-openai:latest
    ports:
      - "8002:8000"  # Changed from 8001
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: --model Qodo/Qodo-Embed-1-1.5B --trust-remote-code

  code-search-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${CODE_SEARCH_API_PORT:-8003}:8000"  # Changed default from 8000 to 8003
    depends_on:
      - qdrant
      - embedder
    environment:
      - PORT=8000
      - QDRANT_URL=http://qdrant:6333  # Internal port remains the same
      - EMBEDDER_URL=http://embedder:8000/v1/embeddings  # Internal port remains the same
      - CONFIG_PATH=/app/config.json
    volumes:
      - ./repos_config.json:/app/config.json
      - ./data:/app/data
